/**
 * QADR Reporter for GitHub Action
 *
 * Generates reports and posts comments to pull requests.
 */

import * as core from '@actions/core';
import * as github from '@actions/github';
import type { ActionInputs } from './inputs';
import type { ActionResult } from './main';

/**
 * Report generator and poster
 */
export class Reporter {
  private octokit: ReturnType<typeof github.getOctokit> | null = null;

  constructor(private inputs: ActionInputs) {
    if (inputs.token) {
      this.octokit = github.getOctokit(inputs.token);
    }
  }

  /**
   * Generate and post report
   */
  async report(result: ActionResult): Promise<void> {
    // Generate summary
    const summary = this.generateSummary(result);

    // Write to job summary
    await core.summary.addRaw(summary).write();

    // Post to PR if applicable
    if (this.shouldPostComment()) {
      await this.postComment(summary);
    }
  }

  /**
   * Generate markdown summary
   */
  private generateSummary(result: ActionResult): string {
    const lines: string[] = [];

    lines.push('# 🔮 QADR Dependency Report');
    lines.push('');

    if (result.mode === 'resolve' && result.resolution) {
      lines.push('## 📦 Resolution Results');
      lines.push('');
      lines.push(`| Metric | Value |`);
      lines.push(`| ------ | ----- |`);
      lines.push(`| Total Packages | ${result.resolution.packages.length} |`);
      lines.push(`| Conflicts | ${result.resolution.conflicts.length} |`);
      lines.push(`| Duration | ${result.resolution.duration}ms |`);
      lines.push(`| Cache Hit | ${result.cacheHit ? '✅' : '❌'} |`);
      lines.push('');
    }

    if (result.analysis) {
      lines.push('## 🔍 Analysis Results');
      lines.push('');

      // Vulnerabilities
      if (result.analysis.vulnerabilities.length > 0) {
        lines.push('### 🛡️ Vulnerabilities');
        lines.push('');
        lines.push('| Package | Severity | Title |');
        lines.push('| ------- | -------- | ----- |');

        for (const vuln of result.analysis.vulnerabilities) {
          const severityBadge = this.getSeverityBadge(vuln.severity);
          lines.push(`| ${vuln.package} | ${severityBadge} | ${vuln.title} |`);
        }
        lines.push('');
      } else {
        lines.push('### ✅ No vulnerabilities found');
        lines.push('');
      }

      // Outdated
      if (result.analysis.outdated.length > 0) {
        lines.push('### 📦 Outdated Packages');
        lines.push('');
        lines.push('| Package | Current | Latest | Type |');
        lines.push('| ------- | ------- | ------ | ---- |');

        for (const pkg of result.analysis.outdated) {
          lines.push(`| ${pkg.name} | ${pkg.current} | ${pkg.latest} | ${pkg.type} |`);
        }
        lines.push('');
      }
    }

    if (result.benchmark) {
      lines.push('## 📈 Benchmark Results');
      lines.push('');
      lines.push('| Metric | QADR | Baseline | Improvement |');
      lines.push('| ------ | ---- | -------- | ----------- |');
      lines.push(
        `| Duration | ${result.benchmark.qadr.duration}ms | ${result.benchmark.baseline.duration}ms | **${result.benchmark.speedup.toFixed(2)}x faster** |`
      );
      lines.push(
        `| Memory | ${result.benchmark.qadr.memory}MB | ${result.benchmark.baseline.memory}MB | **${result.benchmark.memoryReduction.toFixed(1)}% less** |`
      );
      lines.push('');
    }

    lines.push('---');
    lines.push('*Generated by [QADR](https://github.com/iamthegreatdestroyer/QADR)*');

    return lines.join('\n');
  }

  /**
   * Get severity badge
   */
  private getSeverityBadge(severity: string): string {
    const badges: Record<string, string> = {
      critical: '🔴 Critical',
      high: '🟠 High',
      medium: '🟡 Medium',
      low: '🟢 Low',
    };
    return badges[severity] || severity;
  }

  /**
   * Check if we should post a comment
   */
  private shouldPostComment(): boolean {
    const context = github.context;
    return (
      this.octokit !== null &&
      (context.eventName === 'pull_request' ||
        context.eventName === 'pull_request_target')
    );
  }

  /**
   * Post comment to PR
   */
  private async postComment(body: string): Promise<void> {
    if (!this.octokit) {
      return;
    }

    const context = github.context;

    if (!context.payload.pull_request) {
      return;
    }

    try {
      // Find existing comment
      const { data: comments } = await this.octokit.rest.issues.listComments({
        ...context.repo,
        issue_number: context.payload.pull_request.number,
      });

      const existingComment = comments.find(
        (comment) =>
          comment.user?.login === 'github-actions[bot]' &&
          comment.body?.includes('QADR Dependency Report')
      );

      if (existingComment) {
        // Update existing comment
        await this.octokit.rest.issues.updateComment({
          ...context.repo,
          comment_id: existingComment.id,
          body,
        });
        core.info('📝 Updated existing PR comment');
      } else {
        // Create new comment
        await this.octokit.rest.issues.createComment({
          ...context.repo,
          issue_number: context.payload.pull_request.number,
          body,
        });
        core.info('📝 Created new PR comment');
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      core.warning(`Failed to post PR comment: ${message}`);
    }
  }
}
